# Generated by Django 3.2.1 on 2021-05-04 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('idanswer', models.IntegerField(primary_key=True, serialize=False)),
                ('idquestion', models.IntegerField()),
                ('idwriter', models.IntegerField()),
                ('totalpoints', models.IntegerField(blank=True, null=True)),
                ('numberofevaluations', models.IntegerField(blank=True, null=True)),
                ('upvotes', models.IntegerField(blank=True, null=True)),
                ('downvotes', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'answer',
                'managed': False,
            },
        ),
    ]
