# Generated by Django 3.2.1 on 2021-05-04 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('idquestion', models.IntegerField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=255, unique=True)),
                ('iddomain', models.IntegerField()),
                ('asked', models.IntegerField()),
            ],
            options={
                'db_table': 'question',
                'managed': False,
            },
        ),
    ]
